services:
  freshmanragbot:
    image: ghcr.io/shkalikovoleh/freshmanrag_bot:latest
    restart: always
    depends_on:
      - db
    networks:
      - bot-network
    volumes:
      - ${PWD}/.models/:/app/.models
    env_file:
      - .env
  db:
    image: pgvector/pgvector:pg16
    restart: always
    env_file:
      - .env
    networks:
      - bot-network
    volumes:
      - ${PWD}/data/db-data/:/var/lib/postgresql/data/
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 127.0.0.1:15433:80
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - bot-network
    volumes:
      - ${PWD}/data/pgadmin-data/:/var/lib/pgadmin/
networks:
  bot-network:
    driver: bridge
